# Generated by Django 5.2.6 on 2025-09-21 19:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appelderlink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='agenda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='unique_paciente_periodo',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='data_inicial',
        ),
        migrations.AddField(
            model_name='agenda',
            name='duracao_consulta',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fim',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='periodo',
            name='inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='appelderlink.paciente'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='appelderlink.medico'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='appelderlink.paciente'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('nome', 'estado'), name='unique_cidade_estado'),
        ),
        migrations.AddField(
            model_name='horario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='appelderlink.periodo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='appelderlink.horario'),
        ),
    ]
